language: php
php:
- '7.4'
- 'nightly'
jobs:
  allow_failures:
    - php: 'nightly'
before_script:
- composer require --dev phpunit/phpunit $PHPUNIT_VERSION
- composer require --dev phpunit/php-code-coverage
- phpenv config-rm xdebug.ini
script:
- ./vendor/bin/phpunit --configuration travisci-phpunit.xml --no-configuration tests
before_deploy:
- cd ..
- mkdir packages
- zip -r packages/tpl_gileba.zip tpl_gileba/src -x \*.git\*
- git clone -b 1.0.0 https://github.com/Gileba/plg_system_templatecompanion.git plg_system_templatecompanion
- cd plg_system_templatecompanion/src; zip -r ../../packages/plg_system_templatecompanion.zip * -x \*.git\* *.gitignore*; cd ../../
- cp tpl_gileba/pkg_gileba.xml pkg_gileba.xml
- zip pkg_gileba packages/tpl_gileba.zip packages/plg_system_templatecompanion.zip pkg_gileba.xml
deploy:
  provider: releases
  edge: true
  file:
  - packages/tpl_gileba.zip
  - pkg_gileba.zip
  on:
    tags: true
  token: $GITHUB_TOKEN
after_deploy: curl -T tpl_gileba/tpl_gileba.xml -u $FTP_USER:$FTP_PASSWORD $FTP_SERVER
